name: Build Image Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_x86:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev

    - name: Build
      run: make -C Tests/ImageTests

  build_arm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-aarch64-linux-gnu make libgtest-dev

    - name: Build
      run: make -C "Tests/ImageTests CXX=aarch64-linux-gnu-g++ arm"
